### ISSUE TITLE
Add Mastodon link to website

### ISSUE THREAD

**Issue by ns-rse** [SheffieldR/SheffieldR.github.io#23]
Now we have [@sheffieldr@fosstodon.org](https://fosstodon.org/@sheffieldr) setup and tooting the RSS feed from the site we need to add a button to the website to Mastodon.

This can be done by adding the following entry to `_quarto.yaml`.

```yaml
website:
  navbar:
    right:
      - icon: mastodon
        href: https://fosstodon.org/@sheffieldr
        rel: me
```

The `rel: me` bit will mean that the website, which has been added to the profile on Mastodon is marked as verified.
